retail2025:  # 👈 Nom du projet dbt
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project:  # 👈 Ton ID projet GCP
      dataset:  # 👈 Nom du dataset BigQuery
      threads: 1
      timeout_seconds: 300
      location: EU
      keyfile: # 👈 Path to your keyfile

